window:
  title: terminal
  dimensions:
    columns: 85
    lines: 24
  padding:
    x: 15
    y: 15
  #opacity: 0.95

cursor:
  style:
    shape: Block  #Block, Underline, Beam
    blinking: Off
    blink_interval: 300
    blink_timeout: 0

scrolling:
  history: 20000
  multiplier: 3

font:
#  size: 8
  size: 9
  normal:
    family: JetBrains Mono
#    family: Fira Code
    style: Regular
#    style: Medium
  bold:
    family: JetBrains Mono
#    family: Fira Code
    style: Bold
  italic:
    family: JetBrains Mono
#    family: Fira Code
    style: Italic
  bold_italic:
    family: JetBrains Mono
#    family: Fira Code
    style: Bold Italic

draw_bold_text_with_bright_colors: true

import:
  - ~/.config/alacritty/solarized-osaka.yml

key_bindings:
  - { key: Return, mods: Super|Shift, action: SpawnNewInstance }
