#!/bin/bash

Icon1="🛜"
Icon2="🚫"

Name=$(nmcli dev status | awk NR==2'{print $4}')
Status=$(nmcli dev status | awk NR==3'{print $3}')

if [ "$Status" = "connected" ] ; then
	echo " $Icon1 $Name "
else
	echo " $Icon2 $Icon1 - "
fi
