#!/bin/bash

export PATH="${PATH}:$HOME/.config/sxstatus/modules"

while true; do
        xsetroot -name "$(uptime_sx)|$(bright_sx)|$(temp_sx)|$(wifi_sx)|$(memory_sx)|$(battery_sx)|$(volume_sx)|$(clock_sx)"
        sleep 6
done
